server:
  port: 3333
  servlet:
    context-path: /warehouse
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_warehouse?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1314gggg
  redis:
    database: 1
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    # 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名
    map-underscore-to-camel-case: true
  # 类型别名
  type-aliases-package: net.wanho.po
  # mapper 扫描
  mapper-locations: classpath:mapper/*Mapper.xml
warehouse:
  jwt:
    expire: 30
    secret: "wanho"



